-- ICT1222 Mini Project - Attendance Stored Procedures
-- Procedures for attendance management

-- Example procedure:
-- DELIMITER //
-- CREATE PROCEDURE mark_attendance(
--     IN p_student_id INT,
--     IN p_class_id INT,
--     IN p_status VARCHAR(20)
-- )
-- BEGIN
--     INSERT INTO attendance (student_id, class_id, status, date)
--     VALUES (p_student_id, p_class_id, p_status, CURDATE());
-- END //
-- DELIMITER ;
