-- ICT1222 Mini Project - Marks Stored Procedures
-- Procedures for marks management

-- Example procedure:
-- DELIMITER //
-- CREATE PROCEDURE add_marks(
--     IN p_student_id INT,
--     IN p_subject_id INT,
--     IN p_marks DECIMAL(5,2)
-- )
-- BEGIN
--     INSERT INTO marks (student_id, subject_id, marks, date)
--     VALUES (p_student_id, p_subject_id, p_marks, CURDATE());
-- END //
-- DELIMITER ;
