-- ICT1222 Mini Project - Attendance Views
-- Views related to attendance tracking

-- Example view:
-- CREATE OR REPLACE VIEW student_attendance_summary AS
-- SELECT 
--     student_id,
--     COUNT(*) as total_classes,
--     SUM(CASE WHEN status = 'present' THEN 1 ELSE 0 END) as present_count
-- FROM attendance
-- GROUP BY student_id;
